# Amazon AtoZ Credentials

ATOZ_USERNAME='smithjkw'
ATOZ_PASSWORD='smithyjohn1234!'

# Alexa/Echo Dot 'My Notifications' token

NOTIFICATIONS_TOKEN='amzn1.ask.account.AFEAOJZMK8900923BGHI32BIWFRCLP2SZFZAXAWMQXBLPHKX24YSQGNSD33RSVARHDRVFBESNUZTZEOF5TFVQMXT5PVEZDCYRPHMYX6VCDA4ZWU76YQFTR5ZM6EEDT3V3GSJPFWUVGRRGJYP5PTMQWKUH6S6TCS3EEN4IGDQ6DY'

# Voicemonkey Token - see https://voicemonkey.io
VOICEMONKEY_TOKEN=''

